# Generated by Django 5.1.5 on 2025-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='brand',
            field=models.CharField(choices=[('Blizzard', 'Blizzard'), ('Epic', 'Epic'), ('Microsoft', 'Microsoft'), ('Nintendo', 'Nintendo'), ('Sony', 'Sony'), ('Steam', 'Steam')], default='Blizzard'),
        ),
    ]
