# Generated by Django 5.1.5 on 2025-01-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_platform_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['fav_rank']},
        ),
        migrations.AlterField(
            model_name='genre_scores',
            name='profile_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main_app.profile'),
        ),
    ]
