# Generated by Django 5.1.5 on 2025-01-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_likes',
            field=models.JSONField(default=list),
        ),
    ]
