# Generated by Django 5.1.5 on 2025-01-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_likes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
