# Generated by Django 5.1.5 on 2025-01-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_profile_location_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
