# Generated by Django 5.1.5 on 2025-01-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.JSONField(default=list),
        ),
    ]
